# Generated by Django 5.2.7 on 2025-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe_card', 'Stripe Card'), ('stripe_bank', 'Stripe Bank Transfer'), ('paypal', 'PayPal'), ('payme', 'Payme'), ('click', 'Click'), ('yandex', 'Yandex.Kassa / YooMoney'), ('alipay', 'Alipay'), ('wechat', 'WeChat Pay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
