# Generated by Django 5.2.5 on 2025-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Hisoblangan oylik maosh summasi', max_digits=12)),
                ('month', models.DateField(help_text='Oylik maosh qaysi oy uchun ekanligi (masalan, 2025-08-01)')),
                ('status', models.CharField(choices=[('calculated', 'Hisoblangan'), ('paid', "To'langan"), ('rejected', 'Bekor qilingan')], default='calculated', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month', 'teacher'],
            },
        ),
    ]
