# Generated by Django 5.2.5 on 2025-08-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('student_profile', '0003_automaticfine_paymenttype_payment_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField(help_text='Qaysi oy uchun hisoblanganligi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_for_mentor', to='student_profile.group')),
                ('mentor', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='group_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'mentor'],
                'unique_together': {('mentor', 'group', 'month')},
            },
        ),
    ]
