# Generated by Django 5.2.5 on 2025-08-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.branch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.course'),
        ),
    ]
