"""
IELTS Exam Draft and Approval System
Allows staff to create exams with AI review and LMS head approval
"""

from django.db import models
from django.conf import settings
from django.utils import timezone
from .ielts_models import IELTSExam, IELTSQuestion


class ExamDraftStatus(models.TextChoices):
    DRAFT = 'draft', 'Draft'
    AI_REVIEWING = 'ai_reviewing', 'AI Reviewing'
    AI_REVIEWED = 'ai_reviewed', 'AI Reviewed'
    PENDING_APPROVAL = 'pending_approval', 'Pending Approval'
    APPROVED = 'approved', 'Approved'
    REJECTED = 'rejected', 'Rejected'
    PUBLISHED = 'published', 'Published'


class IELTSExamDraft(models.Model):
    """
    Draft version of IELTS exam before approval
    """
    # Creator info
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='created_exam_drafts'
    )

    # Exam details (same as IELTSExam)
    section = models.CharField(max_length=20, choices=[
        ('reading', 'Reading'),
        ('listening', 'Listening'),
        ('writing', 'Writing'),
        ('speaking', 'Speaking'),
    ])
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    # Pricing
    coin_cost = models.PositiveIntegerField(default=50)
    coin_refund = models.PositiveIntegerField(default=10)

    # Settings
    time_limit_minutes = models.PositiveIntegerField()
    passing_band_score = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        default=5.0
    )
    instructions = models.TextField(blank=True)

    # Workflow status
    status = models.CharField(
        max_length=20,
        choices=ExamDraftStatus.choices,
        default=ExamDraftStatus.DRAFT
    )

    # AI Review
    ai_reviewed_at = models.DateTimeField(null=True, blank=True)
    ai_suggestions = models.JSONField(
        default=dict,
        blank=True,
        help_text='AI feedback and suggestions'
    )
    ai_quality_score = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        null=True,
        blank=True,
        help_text='AI quality assessment (0-100)'
    )

    # Approval workflow
    submitted_for_review_at = models.DateTimeField(null=True, blank=True)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_exam_drafts'
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    review_comments = models.TextField(blank=True)

    # If approved, link to published exam
    published_exam = models.OneToOneField(
        IELTSExam,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='draft_source'
    )
    published_at = models.DateTimeField(null=True, blank=True)

    # Metadata
    version = models.PositiveIntegerField(default=1)
    is_ai_generated = models.BooleanField(
        default=False,
        help_text='Was this exam generated by AI?'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'IELTS Exam Draft'
        verbose_name_plural = 'IELTS Exam Drafts'
        indexes = [
            models.Index(fields=['status', 'section']),
            models.Index(fields=['created_by', 'status']),
        ]

    def __str__(self):
        return f"{self.title} - {self.get_status_display()}"

    def submit_for_ai_review(self):
        """Submit exam draft for AI review"""
        self.status = ExamDraftStatus.AI_REVIEWING
        self.submitted_for_review_at = timezone.now()
        self.save()

        # Trigger AI review task
        from .exam_draft_tasks import review_exam_with_ai
        review_exam_with_ai.delay(self.id)

    def submit_for_approval(self):
        """Submit AI-reviewed exam for LMS head approval"""
        if self.status != ExamDraftStatus.AI_REVIEWED:
            raise ValueError('Exam must be AI-reviewed before submission for approval')

        self.status = ExamDraftStatus.PENDING_APPROVAL
        self.save()

        # Create notification for LMS heads
        from .notification_models import Notification
        Notification.create_exam_approval_request(self)

    def approve(self, reviewed_by, comments=''):
        """Approve exam and publish it"""
        self.status = ExamDraftStatus.APPROVED
        self.reviewed_by = reviewed_by
        self.reviewed_at = timezone.now()
        self.review_comments = comments
        self.save()

        # Publish the exam
        self.publish()

    def reject(self, reviewed_by, comments):
        """Reject exam draft"""
        self.status = ExamDraftStatus.REJECTED
        self.reviewed_by = reviewed_by
        self.reviewed_at = timezone.now()
        self.review_comments = comments
        self.save()

        # Notify creator
        from .notification_models import Notification
        Notification.create_exam_rejected(self)

    def publish(self):
        """Convert draft to published exam"""
        if self.status != ExamDraftStatus.APPROVED:
            raise ValueError('Only approved exams can be published')

        # Create actual exam
        exam = IELTSExam.objects.create(
            section=self.section,
            title=self.title,
            description=self.description,
            coin_cost=self.coin_cost,
            coin_refund=self.coin_refund,
            time_limit_minutes=self.time_limit_minutes,
            passing_band_score=self.passing_band_score,
            instructions=self.instructions,
            is_active=True
        )

        # Copy questions from draft to published exam
        draft_questions = self.draft_questions.all()
        for draft_q in draft_questions:
            IELTSQuestion.objects.create(
                exam=exam,
                question_type=draft_q.question_type,
                order=draft_q.order,
                passage_text=draft_q.passage_text,
                audio_file=draft_q.audio_file,
                question_text=draft_q.question_text,
                options=draft_q.options,
                correct_answer=draft_q.correct_answer,
                points=draft_q.points,
                speaking_prompts=draft_q.speaking_prompts,
                time_limit_seconds=draft_q.time_limit_seconds
            )

        # Link draft to published exam
        self.published_exam = exam
        self.status = ExamDraftStatus.PUBLISHED
        self.published_at = timezone.now()
        self.save()

        # Notify creator
        from .notification_models import Notification
        Notification.create_exam_published(self)

        return exam


class IELTSQuestionDraft(models.Model):
    """
    Draft questions for exam draft
    """
    exam_draft = models.ForeignKey(
        IELTSExamDraft,
        on_delete=models.CASCADE,
        related_name='draft_questions'
    )

    # Same fields as IELTSQuestion
    question_type = models.CharField(max_length=50)
    order = models.PositiveIntegerField(default=0)

    passage_text = models.TextField(blank=True)
    audio_file = models.FileField(
        upload_to='ielts/drafts/audio/%Y/%m/',
        blank=True,
        null=True
    )
    question_text = models.TextField()

    options = models.JSONField(default=list, blank=True)
    correct_answer = models.JSONField(default=dict)

    points = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        default=1.0
    )

    speaking_prompts = models.JSONField(default=list, blank=True)
    time_limit_seconds = models.PositiveIntegerField(default=0)

    # AI feedback for this specific question
    ai_feedback = models.JSONField(
        default=dict,
        blank=True,
        help_text='AI suggestions for this question'
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['exam_draft', 'order']
        verbose_name = 'IELTS Question Draft'
        verbose_name_plural = 'IELTS Question Drafts'

    def __str__(self):
        return f"{self.exam_draft.title} - Q{self.order}"


class AIExamGenerationRequest(models.Model):
    """
    Track AI exam generation requests
    """
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='ai_exam_requests'
    )

    section = models.CharField(max_length=20)
    difficulty_level = models.CharField(
        max_length=20,
        choices=[
            ('easy', 'Easy'),
            ('medium', 'Medium'),
            ('hard', 'Hard'),
        ],
        default='medium'
    )

    # Generation parameters
    topic = models.CharField(max_length=255, blank=True)
    custom_instructions = models.TextField(blank=True)

    # Result
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Pending'),
            ('generating', 'Generating'),
            ('completed', 'Completed'),
            ('failed', 'Failed'),
        ],
        default='pending'
    )

    generated_draft = models.ForeignKey(
        IELTSExamDraft,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generation_request'
    )

    error_message = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'AI Exam Generation Request'
        verbose_name_plural = 'AI Exam Generation Requests'

    def __str__(self):
        return f"AI Generate {self.section} - {self.get_status_display()}"
