# Generated by Django 5.2.7 on 2025-10-24 10:40

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='PlatformKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('category', models.CharField(choices=[('crm', 'CRM Features'), ('lms', 'LMS Features'), ('erp', 'ERP Features'), ('workflow', 'Workflows & Processes'), ('feature', 'Platform Features'), ('faq', 'Frequently Asked Questions'), ('tutorial', 'Tutorials & Guides'), ('troubleshooting', 'Troubleshooting'), ('api', 'API Documentation'), ('general', 'General Information')], db_index=True, max_length=50)),
                ('title', models.CharField(help_text='Short title/summary', max_length=255)),
                ('content', models.TextField(help_text='Detailed knowledge content')),
                ('keywords', models.JSONField(default=list, help_text='Keywords for search')),
                ('language', models.CharField(db_index=True, default='en', max_length=5)),
                ('translations', models.JSONField(default=dict, help_text='Translations in other languages')),
                ('source', models.CharField(help_text='Where this knowledge came from', max_length=50)),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence in this knowledge (0-1)')),
                ('verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('times_used', models.IntegerField(default=0, help_text='How many times this was helpful')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
            ],
            options={
                'verbose_name': 'Platform Knowledge',
                'verbose_name_plural': 'Platform Knowledge',
                'ordering': ['-confidence_score', '-times_used', '-created_at'],
                'indexes': [models.Index(fields=['category', '-confidence_score'], name='ai_platform_categor_f7ef47_idx'), models.Index(fields=['language', 'category'], name='ai_platform_languag_c1d64a_idx'), django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='ai_platform_keyword_3e0fe9_gin')],
            },
        ),
        migrations.CreateModel(
            name='ConversationLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('learned_topic', models.CharField(max_length=255)),
                ('learned_content', models.TextField()),
                ('category', models.CharField(choices=[('crm', 'CRM Features'), ('lms', 'LMS Features'), ('erp', 'ERP Features'), ('workflow', 'Workflows & Processes'), ('feature', 'Platform Features'), ('faq', 'Frequently Asked Questions'), ('tutorial', 'Tutorials & Guides'), ('troubleshooting', 'Troubleshooting'), ('api', 'API Documentation'), ('general', 'General Information')], max_length=50)),
                ('user_query', models.TextField(help_text='Original user question')),
                ('llm_response', models.TextField(help_text='LLM response that was helpful')),
                ('was_helpful', models.BooleanField(default=False, help_text='User confirmed it was helpful')),
                ('extracted_to_kb', models.BooleanField(default=False, help_text='Extracted to knowledge base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_from', to='ai.platformknowledge')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation_id', '-created_at'], name='ai_conversa_convers_dd5082_idx'), models.Index(fields=['category', 'was_helpful'], name='ai_conversa_categor_851c3c_idx')],
            },
        ),
    ]
