# Generated by Django 5.2.7 on 2025-11-15 14:58

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_indexing_status_94fdb2_idx'), models.Index(fields=['content_type', 'object_id'], name='ai_indexing_content_c0a67f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('content_type', models.CharField(db_index=True, help_text="Model type: 'user', 'course', 'lead', etc.", max_length=50)),
                ('object_id', models.BigIntegerField(db_index=True, help_text='ID of the indexed object')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for exact matching')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='384-dimensional vector from all-MiniLM-L6-v2')),
                ('branch_id', models.BigIntegerField(blank=True, db_index=True, help_text='Filter by branch (null = global)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('required_roles', models.JSONField(default=list, help_text="Required roles to see this result: ['teacher', 'admin', 'student']")),
                ('metadata', models.JSONField(default=dict, help_text='Additional data specific to content type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Index',
                'verbose_name_plural': 'Search Indexes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ai_searchin_content_caf001_idx'), models.Index(fields=['branch_id', 'is_active'], name='ai_searchin_branch__89df53_idx'), models.Index(fields=['content_type', 'is_active'], name='ai_searchin_content_688ebe_idx'), django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='ai_searchin_keyword_e7ca03_gin')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Embedding of the query for similarity search')),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_result_ids', models.JSONField(default=list, help_text='List of SearchIndex IDs that were clicked')),
                ('was_helpful', models.BooleanField(blank=True, help_text='User feedback: was this search helpful?', null=True)),
                ('rephrased_query', models.TextField(blank=True, help_text='If user rephrased, store new query (negative signal)')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Search processing time in milliseconds')),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters used: content_types, branch_id, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_searchqu_user_id_ed8771_idx'), models.Index(fields=['was_helpful'], name='ai_searchqu_was_hel_eda670_idx')],
            },
        ),
    ]
