"""
Analytics Models - Complete Implementation
Comprehensive analytics tracking for the educational platform
"""

from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models import Avg, Sum, Count, Q, F
from datetime import timedelta

User = get_user_model()


class AnalyticsSnapshot(models.Model):
    """
    Daily snapshot of platform metrics.{student_name},{date},{verification_code},{}
    Automatically generated by Celery or management command.
    """
    date = models.DateField(unique=True, db_index=True, help_text="Date of this snapshot")

    # User metrics
    total_users = models.PositiveIntegerField(default=0)
    total_students = models.PositiveIntegerField(default=0)
    total_teachers = models.PositiveIntegerField(default=0)
    active_students = models.PositiveIntegerField(default=0, help_text="Students who logged in this month")
    new_users_today = models.PositiveIntegerField(default=0)

    # Course & Group metrics
    total_groups = models.PositiveIntegerField(default=0)
    total_courses = models.PositiveIntegerField(default=0)
    active_groups = models.PositiveIntegerField(default=0, help_text="Groups with sessions this month")

    # Attendance metrics
    attendance_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0, help_text="Average attendance percentage")
    total_classes_held = models.PositiveIntegerField(default=0)

    # Performance metrics
    average_exam_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    passing_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0, help_text="Percentage of students passing exams")

    # Financial metrics (in tiyin)
    daily_revenue = models.BigIntegerField(default=0)
    daily_expenses = models.BigIntegerField(default=0)
    daily_profit = models.BigIntegerField(default=0)
    pending_payments = models.BigIntegerField(default=0)

    # CRM metrics
    total_leads = models.PositiveIntegerField(default=0)
    active_leads = models.PositiveIntegerField(default=0)
    converted_leads_today = models.PositiveIntegerField(default=0)
    conversion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    # Engagement metrics
    active_sessions = models.PositiveIntegerField(default=0, help_text="Active user sessions")
    avg_session_duration = models.PositiveIntegerField(default=0, help_text="Average session duration in seconds")
    total_logins = models.PositiveIntegerField(default=0)

    # System metrics
    total_tasks = models.PositiveIntegerField(default=0)
    pending_tasks = models.PositiveIntegerField(default=0)
    completed_tasks = models.PositiveIntegerField(default=0)

    # Metadata
    calculated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']
        verbose_name = "Analytics Snapshot"
        verbose_name_plural = "Analytics Snapshots"
        indexes = [
            models.Index(fields=['-date']),
        ]

    def __str__(self):
        return f"Analytics Snapshot - {self.date}"

    @classmethod
    def generate_snapshot(cls, date=None):
        """Generate analytics snapshot for a specific date"""
        if date is None:
            date = timezone.now().date()

        from student_profile.models import Group, Course, Attendance, ExamScore, Payment, Expense
        from crm.models import Lead
        from task.models import Task

        # Calculate date range
        start_of_day = timezone.make_aware(timezone.datetime.combine(date, timezone.datetime.min.time()))
        end_of_day = start_of_day + timedelta(days=1)
        start_of_month = start_of_day.replace(day=1)

        # User metrics
        total_users = User.objects.filter(is_active=True).count()
        total_students = User.objects.filter(is_teacher=False, is_staff=False, is_active=True).count()
        total_teachers = User.objects.filter(is_teacher=True, is_active=True).count()
        new_users_today = User.objects.filter(date_joined__gte=start_of_day, date_joined__lt=end_of_day).count()

        # Active students (logged in this month)
        # This would require session tracking - placeholder for now
        active_students = total_students

        # Group & Course metrics
        total_groups = Group.objects.count()
        total_courses = Course.objects.count()
        active_groups = Group.objects.filter(
            start_day__lte=date,
            end_day__gte=date
        ).count()

        # Attendance metrics
        attendances_today = Attendance.objects.filter(date=date)
        total_classes = attendances_today.count()
        if total_classes > 0:
            present = attendances_today.filter(is_present=True).count()
            attendance_rate = (present / total_classes) * 100
        else:
            attendance_rate = 0

        # Performance metrics
        exam_scores_month = ExamScore.objects.filter(date__gte=start_of_month, date__lte=date)
        avg_score = exam_scores_month.aggregate(avg=Avg('score'))['avg'] or 0

        if exam_scores_month.exists():
            passing = exam_scores_month.filter(score__gte=60).count()
            passing_rate = (passing / exam_scores_month.count()) * 100
        else:
            passing_rate = 0

        # Financial metrics
        payments_today = Payment.objects.filter(
            date=date,
            status='paid'
        )
        daily_revenue = payments_today.aggregate(total=Sum('amount'))['total'] or 0

        expenses_today = Expense.objects.filter(date=date)
        daily_expenses = expenses_today.aggregate(total=Sum('amount'))['total'] or 0

        daily_profit = daily_revenue - daily_expenses

        pending = Payment.objects.filter(status='pending').aggregate(total=Sum('amount'))['total'] or 0

        # CRM metrics
        total_leads = Lead.objects.count()
        active_leads = Lead.objects.filter(status='in_progress').count()
        converted_today = Lead.objects.filter(
            status='converted',
            created_at__gte=start_of_day,
            created_at__lt=end_of_day
        ).count()

        leads_month = Lead.objects.filter(created_at__gte=start_of_month)
        if leads_month.exists():
            converted_month = leads_month.filter(status='converted').count()
            conversion_rate = (converted_month / leads_month.count()) * 100
        else:
            conversion_rate = 0

        # Task metrics
        try:
            total_tasks = Task.objects.count()
            pending_tasks = Task.objects.filter(is_done=False).count()
            completed_tasks = Task.objects.filter(is_done=True).count()
        except:
            total_tasks = pending_tasks = completed_tasks = 0

        # Create or update snapshot
        snapshot, created = cls.objects.update_or_create(
            date=date,
            defaults={
                'total_users': total_users,
                'total_students': total_students,
                'total_teachers': total_teachers,
                'active_students': active_students,
                'new_users_today': new_users_today,
                'total_groups': total_groups,
                'total_courses': total_courses,
                'active_groups': active_groups,
                'attendance_rate': attendance_rate,
                'total_classes_held': total_classes,
                'average_exam_score': avg_score,
                'passing_rate': passing_rate,
                'daily_revenue': daily_revenue,
                'daily_expenses': daily_expenses,
                'daily_profit': daily_profit,
                'pending_payments': pending,
                'total_leads': total_leads,
                'active_leads': active_leads,
                'converted_leads_today': converted_today,
                'conversion_rate': conversion_rate,
                'total_tasks': total_tasks,
                'pending_tasks': pending_tasks,
                'completed_tasks': completed_tasks,
            }
        )

        return snapshot


class StudentPerformanceMetrics(models.Model):
    """
    Tracks individual student performance metrics over time
    """
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='performance_metrics')
    date = models.DateField(db_index=True)

    # Academic metrics
    average_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total_exams = models.PositiveIntegerField(default=0)
    passed_exams = models.PositiveIntegerField(default=0)
    failed_exams = models.PositiveIntegerField(default=0)

    # Attendance metrics
    attendance_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total_classes = models.PositiveIntegerField(default=0)
    attended_classes = models.PositiveIntegerField(default=0)
    absent_days = models.PositiveIntegerField(default=0)

    # Engagement metrics
    assignments_submitted = models.PositiveIntegerField(default=0)
    assignments_on_time = models.PositiveIntegerField(default=0)
    quiz_attempts = models.PositiveIntegerField(default=0)

    # Progress metrics
    modules_completed = models.PositiveIntegerField(default=0)
    lessons_completed = models.PositiveIntegerField(default=0)
    total_study_time_minutes = models.PositiveIntegerField(default=0)

    # Ranking
    rank = models.PositiveIntegerField(null=True, blank=True)
    percentile = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Metadata
    calculated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date', 'rank']
        unique_together = ['student', 'date']
        verbose_name = "Student Performance Metric"
        verbose_name_plural = "Student Performance Metrics"
        indexes = [
            models.Index(fields=['student', '-date']),
            models.Index(fields=['-date', 'rank']),
        ]

    def __str__(self):
        return f"{self.student.username} - {self.date} - Score: {self.average_score}"


class TeacherPerformanceMetrics(models.Model):
    """
    Tracks teacher performance and workload metrics
    """
    teacher = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='teacher_performance',
        limit_choices_to={'is_teacher': True}
    )
    date = models.DateField(db_index=True)

    # Workload metrics
    total_groups = models.PositiveIntegerField(default=0)
    total_students = models.PositiveIntegerField(default=0)
    total_hours_week = models.PositiveIntegerField(default=0)

    # Student performance metrics
    student_average_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    student_passing_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    student_attendance_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    # Engagement metrics
    assignments_graded = models.PositiveIntegerField(default=0)
    average_grading_time_hours = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    # Financial metrics (in tiyin)
    total_earnings = models.BigIntegerField(default=0)
    earnings_paid = models.BigIntegerField(default=0)
    earnings_pending = models.BigIntegerField(default=0)

    # Rating (from student feedback)
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    total_reviews = models.PositiveIntegerField(default=0)

    # Metadata
    calculated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date', 'teacher']
        unique_together = ['teacher', 'date']
        verbose_name = "Teacher Performance Metric"
        verbose_name_plural = "Teacher Performance Metrics"
        indexes = [
            models.Index(fields=['teacher', '-date']),
            models.Index(fields=['-date', '-average_rating']),
        ]

    def __str__(self):
        return f"{self.teacher.username} - {self.date}"


class CourseAnalytics(models.Model):
    """
    Analytics for individual courses
    """
    course = models.ForeignKey('student_profile.Course', on_delete=models.CASCADE, related_name='analytics')
    date = models.DateField(db_index=True)

    # Enrollment metrics
    total_enrolled = models.PositiveIntegerField(default=0)
    new_enrollments = models.PositiveIntegerField(default=0)
    active_students = models.PositiveIntegerField(default=0)

    # Completion metrics
    completed_students = models.PositiveIntegerField(default=0)
    in_progress_students = models.PositiveIntegerField(default=0)
    dropped_students = models.PositiveIntegerField(default=0)
    completion_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    # Performance metrics
    average_score = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    passing_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    average_completion_time_days = models.PositiveIntegerField(default=0)

    # Engagement metrics
    average_attendance_rate = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    total_assignments_submitted = models.PositiveIntegerField(default=0)
    total_quiz_attempts = models.PositiveIntegerField(default=0)

    # Financial metrics (in tiyin)
    total_revenue = models.BigIntegerField(default=0)
    average_revenue_per_student = models.BigIntegerField(default=0)

    # Satisfaction
    average_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    total_reviews = models.PositiveIntegerField(default=0)

    # Metadata
    calculated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date', 'course']
        unique_together = ['course', 'date']
        verbose_name = "Course Analytics"
        verbose_name_plural = "Course Analytics"
        indexes = [
            models.Index(fields=['course', '-date']),
            models.Index(fields=['-date', '-total_enrolled']),
        ]

    def __str__(self):
        return f"{self.course.name} - {self.date}"


class Report(models.Model):
    """
    Generated reports storage
    """
    REPORT_TYPES = [
        ('student-performance', 'Student Performance'),
        ('attendance-summary', 'Attendance Summary'),
        ('financial-report', 'Financial Report'),
        ('teacher-workload', 'Teacher Workload'),
        ('course-completion', 'Course Completion'),
        ('enrollment-trends', 'Enrollment Trends'),
        ('custom', 'Custom Report'),
    ]

    REPORT_STATUS = [
        ('generating', 'Generating'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    report_id = models.CharField(max_length=100, unique=True, db_index=True)
    report_type = models.CharField(max_length=50, choices=REPORT_TYPES)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    # Parameters
    period = models.CharField(max_length=20, default='month')
    start_date = models.DateField()
    end_date = models.DateField()

    # Data storage
    summary = models.JSONField(default=dict, help_text="Report summary statistics")
    data = models.JSONField(default=list, help_text="Report detailed data")
    charts = models.JSONField(default=list, help_text="Chart configurations")

    # Status
    status = models.CharField(max_length=20, choices=REPORT_STATUS, default='generating')
    error_message = models.TextField(blank=True)

    # Metadata
    generated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='generated_reports')
    generated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # File storage
    pdf_file = models.FileField(upload_to='reports/pdf/%Y/%m/', blank=True, null=True)
    csv_file = models.FileField(upload_to='reports/csv/%Y/%m/', blank=True, null=True)

    class Meta:
        ordering = ['-generated_at']
        verbose_name = "Report"
        verbose_name_plural = "Reports"
        indexes = [
            models.Index(fields=['-generated_at', 'report_type']),
            models.Index(fields=['generated_by', '-generated_at']),
        ]

    def __str__(self):
        return f"{self.title} - {self.generated_at.strftime('%Y-%m-%d')}"


class UserActivityLog(models.Model):
    """
    Track user activity for engagement analytics
    """
    ACTION_TYPES = [
        ('login', 'Login'),
        ('logout', 'Logout'),
        ('view_course', 'View Course'),
        ('complete_lesson', 'Complete Lesson'),
        ('submit_assignment', 'Submit Assignment'),
        ('take_quiz', 'Take Quiz'),
        ('make_payment', 'Make Payment'),
        ('other', 'Other'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='activity_logs')
    action_type = models.CharField(max_length=50, choices=ACTION_TYPES)
    description = models.TextField(blank=True)

    # Context
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=255, blank=True)
    session_id = models.CharField(max_length=100, blank=True)

    # Related objects (nullable for flexibility)
    content_type = models.ForeignKey(
        'contenttypes.ContentType',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    object_id = models.PositiveIntegerField(null=True, blank=True)

    # Metadata
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "User Activity Log"
        verbose_name_plural = "User Activity Logs"
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['action_type', '-created_at']),
            models.Index(fields=['-created_at']),
        ]

    def __str__(self):
        return f"{self.user.username} - {self.action_type} - {self.created_at}"
