# Generated by Django 5.2.7 on 2025-11-17 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to='achievements/', verbose_name='Icon')),
                ('tiers', models.JSONField(default=list, help_text='List of tiers with requirements, e.g., [{"level": 1, "requirement": 10, "xp": 100}, ...]')),
                ('category', models.CharField(choices=[('learning', 'Learning'), ('social', 'Social'), ('competitive', 'Competitive'), ('creative', 'Creative'), ('supporter', 'Supporter')], default='learning', max_length=30)),
                ('is_secret', models.BooleanField(default=False, verbose_name='Is Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Name (Russian)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Description (Russian)')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Icon')),
                ('badge_type', models.CharField(choices=[('achievement', 'Achievement'), ('milestone', 'Milestone'), ('special', 'Special'), ('seasonal', 'Seasonal'), ('streak', 'Streak')], default='achievement', max_length=20, verbose_name='Badge Type')),
                ('xp_reward', models.IntegerField(default=100, verbose_name='XP Reward')),
                ('coins_reward', models.IntegerField(default=10, verbose_name='Coins Reward')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, verbose_name='Rarity')),
                ('criteria', models.JSONField(default=dict, help_text='Criteria for earning this badge (e.g., {"lessons_completed": 10})')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['display_order', '-rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('lessons', 'Complete Lessons'), ('quiz', 'Take Quizzes'), ('study_time', 'Study Time'), ('perfect_score', 'Perfect Score'), ('social', 'Social Interaction'), ('streak', 'Maintain Streak')], max_length=30, verbose_name='Challenge Type')),
                ('target_value', models.IntegerField(help_text='The goal to achieve (e.g., 5 lessons, 30 minutes)', verbose_name='Target Value')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='XP Reward')),
                ('coins_reward', models.IntegerField(default=5, verbose_name='Coins Reward')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('available_days', models.CharField(default='1234567', help_text='Days of week (1=Monday, 7=Sunday)', max_length=13)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('leaderboard_type', models.CharField(choices=[('xp', 'Total XP'), ('level', 'Level'), ('streak', 'Streak'), ('quiz_score', 'Quiz Score'), ('course_completion', 'Course Completion')], max_length=20)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('branch', 'Branch'), ('course', 'Course'), ('group', 'Group')], default='global', max_length=20)),
                ('time_period', models.CharField(choices=[('all_time', 'All Time'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='all_time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('current_level', models.IntegerField(default=1, verbose_name='Current Level')),
                ('xp_to_next_level', models.IntegerField(default=100, verbose_name='XP to Next Level')),
                ('current_streak_days', models.IntegerField(default=0, verbose_name='Current Streak (Days)')),
                ('longest_streak_days', models.IntegerField(default=0, verbose_name='Longest Streak (Days)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Last Activity Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Level',
                'verbose_name_plural': 'User Levels',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('bonus', 'Bonus'), ('level_up', 'Level Up'), ('penalty', 'Penalty')], default='earn', max_length=20)),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('new_balance', models.IntegerField(verbose_name='New Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.IntegerField(default=0, verbose_name='Current Tier')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Unlocked At')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-current_tier', '-progress'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Earned At')),
                ('is_showcased', models.BooleanField(default=False, verbose_name='Showcase on Profile')),
                ('earned_for', models.TextField(blank=True, verbose_name='Earned For')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now, verbose_name='Date Assigned')),
                ('current_progress', models.IntegerField(default=0, verbose_name='Current Progress')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Challenge',
                'verbose_name_plural': 'User Daily Challenges',
                'ordering': ['-date_assigned', '-is_completed'],
                'indexes': [models.Index(fields=['user', 'date_assigned', 'is_completed'], name='gamificatio_user_id_a1da81_idx')],
                'unique_together': {('user', 'challenge', 'date_assigned')},
            },
        ),
    ]
