# Generated by Django 5.2.5 on 2025-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shablon nomi (masalan, 'Tug'ilgan kun tabrigi')", max_length=255, unique=True)),
                ('text', models.TextField(help_text="Xabar matni. O'zgaruvchilar uchun {student_name} kabi belgilardan foydalaning.")),
            ],
        ),
        migrations.CreateModel(
            name='SmsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Xabar yuborilgan telefon raqam', max_length=20)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Yuborilgan'), ('pending', 'Kutilmoqda'), ('failed', 'Xatolik')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
