# Generated by Django 5.2.5 on 2025-08-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bu avto-xabar nima uchun ekanligi', max_length=255)),
                ('trigger_event', models.CharField(choices=[('birthday', "Tug'ilgan kunida"), ('payment_due', "To'lov kunidan 3 kun oldin"), ('new_group', "Yangi guruhga qo'shilganda")], help_text="Xabarni yuborishga sabab bo'ladigan hodisa", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_template', models.ForeignKey(help_text='Ushbu hodisada yuboriladigan xabar shabloni', on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetemplate')),
            ],
        ),
    ]
