# Generated by Django 5.2.7 on 2025-10-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_automaticmessage'),
        ('student_profile', '0006_question_courseannouncement_coursemodule_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('payment_reminder', 'Payment Reminder'), ('class_reminder', 'Class Reminder'), ('course_complete', 'Course Completion'), ('assignment_due', 'Assignment Due'), ('newsletter', 'Newsletter'), ('custom', 'Custom Template')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='HTML email body')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available variables: {{student_name}}, {{course_name}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, help_text='Leave blank to use default', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Sender name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('recipient_type', models.CharField(choices=[('all_students', 'All Students'), ('all_teachers', 'All Teachers'), ('all_users', 'All Users'), ('specific_course', 'Specific Course'), ('specific_group', 'Specific Group'), ('custom_list', 'Custom List')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Leave blank to send immediately', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('emails_opened', models.PositiveIntegerField(default=0)),
                ('emails_clicked', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('custom_recipients', models.ManyToManyField(blank=True, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('specific_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.course')),
                ('specific_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.group')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('student_enrolled', 'Student Enrolled in Course'), ('payment_due', 'Payment Due Date Approaching'), ('payment_overdue', 'Payment Overdue'), ('class_reminder', 'Class Starting Soon'), ('assignment_due', 'Assignment Due Soon'), ('course_completed', 'Course Completed'), ('inactivity', 'Student Inactive'), ('birthday', 'Birthday')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay after trigger event (0 = immediate)')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Additional conditions for triggering')),
                ('times_triggered', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.emailtemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, help_text='SendGrid/SES message ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.emailcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='messaging_e_campaig_c1ccbc_idx'), models.Index(fields=['recipient', 'created_at'], name='messaging_e_recipie_a716be_idx')],
            },
        ),
    ]
