# Generated by Django 5.2.7 on 2025-10-24 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_emailtemplate_emailcampaign_automatedemail_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique conversation identifier', unique=True)),
                ('conversation_type', models.CharField(choices=[('ai_chat', 'AI Chat'), ('voice_chat', 'Voice Chat'), ('support', 'Support'), ('direct', 'Direct Message')], default='ai_chat', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Conversation title/subject', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (context, settings, etc.)')),
                ('user', models.ForeignKey(help_text='Primary user in conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique message identifier', unique=True)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('system', 'System')], default='user', max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=10)),
                ('content', models.TextField(help_text='Text content or description')),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file', null=True)),
                ('audio_duration', models.FloatField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('file_url', models.URLField(blank=True, help_text='URL to attached file', null=True)),
                ('intent', models.CharField(blank=True, help_text='Detected intent', max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Intent confidence score', null=True)),
                ('entities', models.JSONField(blank=True, default=dict, help_text='Extracted entities')),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider info, processing time, cost, etc.')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_messages', models.IntegerField(default=0)),
                ('ai_messages', models.IntegerField(default=0)),
                ('intents_detected', models.JSONField(default=dict, help_text='Intent name -> count mapping')),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average AI response time in seconds', null=True)),
                ('total_audio_duration', models.FloatField(default=0.0, help_text='Total audio duration in seconds')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, help_text='Total cost in USD', max_digits=10)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='messaging.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_typing', models.BooleanField(default=False)),
                ('typing_in_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User presences',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='messaging_c_user_id_efb130_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_id'], name='messaging_c_convers_05c0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_c_convers_733667_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_id'], name='messaging_c_message_11492a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='messaging_c_sender__5609a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationanalytics',
            unique_together={('conversation', 'date')},
        ),
    ]
