# Generated by Django 5.2.9 on 2026-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_conversation_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('ai_chat', 'AI Chat'), ('voice_chat', 'Voice Chat'), ('support', 'Support'), ('direct', 'Direct Message'), ('platform', 'Platform'), ('sms', 'SMS')], default='platform', max_length=20),
        ),
    ]
