# Generated by Django 5.2.5 on 2025-10-20 04:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0005_alter_automaticfine_amount_alter_course_price_and_more'),
        ('task', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('standard', 'Standard Certificate'), ('honors', 'Certificate with Honors'), ('completion', 'Certificate of Completion'), ('achievement', 'Certificate of Achievement')], default='standard', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('border_color', models.CharField(default='#FFD700', max_length=7)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('hours_completed', models.PositiveIntegerField(default=0)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student_profile.course')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='task.certificate')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
