# Generated by Django 5.2.9 on 2026-01-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_certificatetemplate_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='task.certificatetemplate'),
        ),
    ]
