# Generated by Django 5.2.5 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Talabaning hisoblangan reytingdagi o'rni", null=True),
        ),
    ]
