# Generated by Django 5.2.5 on 2025-08-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_assistantslot_booking'),
        ('users', '0003_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='student_profile.branch'),
        ),
    ]
