# Generated by Django 5.2.5 on 2026-03-06

from django.db import migrations, models


def forward_populate_role(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all().iterator():
        if user.is_superuser:
            role = 'superadmin'
        elif user.is_teacher:
            role = 'teacher'
        elif user.is_staff:
            role = 'admin'
        else:
            role = 'student'

        User.objects.filter(pk=user.pk).update(role=role)


def backward_reset_role(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.all().update(role='student')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('student', 'Student'),
                    ('parent', 'Parent'),
                    ('teacher', 'Teacher'),
                    ('staff', 'Staff'),
                    ('crm_manager', 'CRM Manager'),
                    ('lms_manager', 'LMS Manager'),
                    ('manager', 'Manager'),
                    ('director', 'Director'),
                    ('admin', 'Admin'),
                    ('superadmin', 'Super Admin'),
                ],
                db_index=True,
                default='student',
                help_text='Primary role used by role-based access control matrix.',
                max_length=32,
            ),
        ),
        migrations.RunPython(forward_populate_role, backward_reset_role),
    ]
