# Generated by Django 5.2.5 on 2026-03-19

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def seed_branch_memberships_from_legacy_branch(apps, schema_editor):
    User = apps.get_model('users', 'User')
    BranchMembership = apps.get_model('users', 'BranchMembership')

    users_with_branch = User.objects.exclude(branch_id__isnull=True)
    for user in users_with_branch.iterator():
        membership, created = BranchMembership.objects.get_or_create(
            user_id=user.id,
            branch_id=user.branch_id,
            defaults={
                'role': getattr(user, 'role', None),
                'is_primary': True,
                'is_active': True,
            },
        )

        if created:
            continue

        updates = {}
        if not membership.is_active:
            updates['is_active'] = True

        has_other_primary = BranchMembership.objects.filter(
            user_id=user.id,
            is_primary=True,
            is_active=True,
        ).exclude(id=membership.id).exists()
        if not has_other_primary and not membership.is_primary:
            updates['is_primary'] = True

        if not membership.role and getattr(user, 'role', None):
            updates['role'] = user.role

        if updates:
            BranchMembership.objects.filter(id=membership.id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0029_attendancecharge_companyshareentry_and_more'),
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('crm_manager', 'CRM Manager'), ('lms_manager', 'LMS Manager'), ('manager', 'Manager'), ('director', 'Director'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], help_text='Optional branch-local role override for reporting/admin UIs.', max_length=32, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary branch used when no branch override is provided.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_branch_memberships', to='users.user')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='student_profile.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to='users.user')),
            ],
            options={
                'ordering': ['-is_primary', 'branch__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='branchmembership',
            constraint=models.UniqueConstraint(fields=('user', 'branch'), name='uniq_user_branch_membership'),
        ),
        migrations.AddConstraint(
            model_name='branchmembership',
            constraint=models.UniqueConstraint(condition=Q(is_active=True, is_primary=True), fields=('user',), name='uniq_primary_active_branch_membership_per_user'),
        ),
        migrations.RunPython(seed_branch_memberships_from_legacy_branch, migrations.RunPython.noop),
    ]
