# Generated by Django 5.2.5 on 2025-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_assistantslot_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticfine',
            name='amount',
            field=models.BigIntegerField(help_text='Jarima summasi tiyinlarda'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.BigIntegerField(help_text='Kurs narxi tiyinlarda'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(help_text='Xarajat summasi tiyinlarda'),
        ),
    ]
