# Generated by Django 5.2.7 on 2025-10-31 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0006_question_courseannouncement_coursemodule_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this financial summary', unique=True)),
                ('total_payments', models.BigIntegerField(default=0, help_text='Total payments received in tiyin')),
                ('payment_count', models.PositiveIntegerField(default=0, help_text='Number of payments received')),
                ('total_expenses', models.BigIntegerField(default=0, help_text='Total expenses in tiyin')),
                ('expense_count', models.PositiveIntegerField(default=0, help_text='Number of expense records')),
                ('total_teacher_earnings', models.BigIntegerField(default=0, help_text='Total teacher earnings generated in tiyin')),
                ('teacher_earnings_paid', models.BigIntegerField(default=0, help_text='Total teacher earnings already paid in tiyin')),
                ('total_fines', models.BigIntegerField(default=0, help_text='Total fines applied in tiyin')),
                ('fines_paid', models.BigIntegerField(default=0, help_text='Total fines paid in tiyin')),
                ('gross_revenue', models.BigIntegerField(default=0, help_text='Payments + Fines paid')),
                ('net_profit', models.BigIntegerField(default=0, help_text='Revenue - Expenses - Teacher Earnings')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this summary was last calculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch-specific summary (null = all branches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='student_profile.branch')),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Fine amount in tiyin')),
                ('reason', models.CharField(choices=[('absence', 'Absence from class'), ('late', 'Coming late to class'), ('behavior', 'Behavior issue'), ('other', 'Other reason')], default='absence', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the fine')),
                ('is_paid', models.BooleanField(default=False, help_text='Has this fine been paid?')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_automatic', models.BooleanField(default=False, help_text='Was this fine automatically applied?')),
                ('applied_date', models.DateField(default=django.utils.timezone.now, help_text='Date when fine was applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, help_text='Attendance record that triggered this fine (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='student_profile.attendance')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/teacher who created this fine (if manual)', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_created', to=settings.AUTH_USER_MODEL)),
                ('fine_type', models.ForeignKey(help_text='Type of fine from AutomaticFine definitions', on_delete=django.db.models.deletion.PROTECT, related_name='applied_fines', to='student_profile.automaticfine')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fines', to='student_profile.group')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Fine',
                'verbose_name_plural': 'Student Fines',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.BigIntegerField(help_text='Original payment amount in tiyin')),
                ('percentage_applied', models.PositiveIntegerField(help_text="Teacher's salary percentage (e.g., 40 for 40%)")),
                ('amount', models.BigIntegerField(help_text="Teacher's earning amount in tiyin")),
                ('is_paid_to_teacher', models.BooleanField(default=False, help_text='Has this earning been paid to the teacher?')),
                ('paid_date', models.DateField(blank=True, help_text='Date when teacher received payment', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when earning was generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_earnings', to='student_profile.group')),
                ('payment', models.OneToOneField(help_text='Source payment that generated this earning', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_earning', to='student_profile.payment')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Earning',
                'verbose_name_plural': 'Teacher Earnings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.BigIntegerField(help_text='Total course fee in tiyin (from course price)')),
                ('paid_amount', models.BigIntegerField(default=0, help_text='Total amount paid by student in tiyin')),
                ('fine_amount', models.BigIntegerField(default=0, help_text='Total fines applied in tiyin')),
                ('balance', models.BigIntegerField(help_text='Remaining balance in tiyin (negative = overpaid, positive = debt)')),
                ('is_fully_paid', models.BooleanField(default=False, help_text='True when balance <= 0')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of most recent payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_balances', to='student_profile.group')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Balance',
                'verbose_name_plural': 'Student Balances',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
