# Generated by Django 5.2.7 on 2025-10-31 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0007_add_accounting_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Student Payment'), ('expense', 'Expense'), ('teacher_earning', 'Teacher Earning'), ('fine', 'Student Fine'), ('refund', 'Refund'), ('adjustment', 'Balance Adjustment')], db_index=True, help_text='Type of financial transaction', max_length=20)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('amount', models.BigIntegerField(help_text='Transaction amount in tiyin (positive = income, negative = expense)')),
                ('balance_before', models.BigIntegerField(blank=True, help_text='Balance before transaction (if applicable)', null=True)),
                ('balance_after', models.BigIntegerField(blank=True, help_text='Balance after transaction (if applicable)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (e.g., receipt number)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date of the transaction')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='student_profile.group')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='student_profile.payment')),
                ('student', models.ForeignKey(blank=True, help_text='Student involved in transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher involved in transaction', limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Transaction',
                'verbose_name_plural': 'Account Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-transaction_date', 'transaction_type'], name='student_pro_transac_62557b_idx'), models.Index(fields=['student', '-transaction_date'], name='student_pro_student_d439e5_idx'), models.Index(fields=['teacher', '-transaction_date'], name='student_pro_teacher_b3be47_idx')],
            },
        ),
    ]
