# Generated by Django 5.2.7 on 2025-11-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0009_add_report_scheduling'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentreminder',
            new_name='payment_rem_status_cedbc4_idx',
            old_name='payment_re_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentreminder',
            new_name='payment_rem_payment_dacb04_idx',
            old_name='payment_re_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='reportgeneration',
            new_name='report_gene_status_7351e6_idx',
            old_name='report_gen_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_enabled_a37a33_idx',
            old_name='scheduled_r_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_report__0074f6_idx',
            old_name='scheduled_r_report_t_idx',
        ),
    ]
