# Generated by Django 5.2.7 on 2025-11-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0010_rename_payment_re_status_idx_payment_rem_status_cedbc4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'ordering': ['-created_at']},
        ),
    ]
