# Generated by Django 5.2.7 on 2025-11-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0011_alter_paymenttype_options_alter_shopproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='student_profile.course'),
            preserve_default=False,
        ),
    ]
