# Generated by Django 5.2.7 on 2025-11-15 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0012_alter_group_course_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency')], max_length=2, unique=True)),
                ('description', models.TextField()),
                ('skills_description', models.JSONField(blank=True, default=dict, help_text='Structure: {reading, writing, speaking, listening}')),
            ],
            options={
                'verbose_name': 'CEFR Level',
                'verbose_name_plural': 'CEFR Levels',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, help_text='e.g., English, Uzbek, Russian', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='student_profile.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_preview_url',
            field=models.URLField(blank=True, help_text='Course preview video'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/books/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='book_url',
            field=models.URLField(blank=True, help_text='External book/PDF URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_solution',
            field=models.TextField(blank=True, help_text='Solution code'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_template',
            field=models.TextField(blank=True, help_text='Starting code template'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise_data',
            field=models.JSONField(blank=True, default=dict, help_text="Structure: {type: 'fill_blank'|'matching'|'drag_drop', questions: [...], answers: [...]}"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='minimum_read_time_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Minimum time to spend on article/book'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='programming_language',
            field=models.CharField(blank=True, help_text='python, javascript, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='Test cases for auto-grading'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, help_text='Audio/Video transcript'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('article', 'Article/Text'), ('book', 'eBook/PDF'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('interactive', 'Interactive Exercise'), ('flashcards', 'Flashcards'), ('live_session', 'Live Session'), ('file', 'Downloadable File'), ('code_exercise', 'Coding Exercise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='minimum_watch_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Percentage of video/audio to watch'),
        ),
        migrations.AddField(
            model_name='course',
            name='cefr_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='student_profile.cefrlevel'),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('language', 'Language'), ('math', 'Mathematics'), ('test_prep', 'Test Preparation'), ('it', 'Information Technology'), ('business', 'Business'), ('science', 'Science'), ('other', 'Other')], max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='student_profile.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='student_profile.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_subcategories', to='student_profile.coursecategory'),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField()),
                ('back_text', models.TextField()),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/')),
                ('front_audio', models.FileField(blank=True, null=True, upload_to='flashcards/audio/')),
                ('back_audio', models.FileField(blank=True, null=True, upload_to='flashcards/audio/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='student_profile.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='student_profile.lesson')),
            ],
            options={
                'ordering': ['course', 'lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SATTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('test_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('reading_time', models.PositiveIntegerField(default=65)),
                ('writing_time', models.PositiveIntegerField(default=35)),
                ('math_no_calc_time', models.PositiveIntegerField(default=25)),
                ('math_calc_time', models.PositiveIntegerField(default=55)),
                ('is_official', models.BooleanField(default=False, help_text='Official College Board test')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_tests', to='student_profile.course')),
            ],
            options={
                'verbose_name': 'SAT Test',
                'verbose_name_plural': 'SAT Tests',
                'ordering': ['test_number'],
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='student_profile.coursecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='courses', to='student_profile.skilltag'),
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, help_text='IPA or phonetic', max_length=200)),
                ('part_of_speech', models.CharField(blank=True, help_text='noun, verb, adjective, etc.', max_length=50)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('translation', models.CharField(blank=True, help_text='Uzbek/Russian translation', max_length=200)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/images/')),
                ('tags', models.JSONField(blank=True, default=list, help_text="e.g., ['common', 'academic', 'business']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cefr_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.cefrlevel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='student_profile.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='student_profile.lesson')),
            ],
            options={
                'ordering': ['course', 'word'],
            },
        ),
        migrations.CreateModel(
            name='StudentVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.PositiveIntegerField(default=0, help_text='0-5 scale')),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='student_profile.vocabularyword')),
            ],
            options={
                'verbose_name_plural': 'Student Vocabulary Progress',
                'ordering': ['next_review_date', '-mastery_level'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.PositiveIntegerField(default=0, help_text='0-5 scale')),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='student_profile.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flashcard Progress',
                'ordering': ['next_review_date', '-mastery_level'],
                'unique_together': {('student', 'flashcard')},
            },
        ),
        migrations.CreateModel(
            name='SATSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing and Language'), ('math_no_calc', 'Math (No Calculator)'), ('math_calc', 'Math (Calculator)')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_sections', to='student_profile.quiz')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='student_profile.sattest')),
            ],
            options={
                'ordering': ['test', 'order'],
                'unique_together': {('test', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='SATAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reading_score', models.PositiveIntegerField(blank=True, null=True)),
                ('writing_score', models.PositiveIntegerField(blank=True, null=True)),
                ('math_score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(blank=True, help_text='400-1600', null=True)),
                ('reading_correct', models.PositiveIntegerField(default=0)),
                ('writing_correct', models.PositiveIntegerField(default=0)),
                ('math_no_calc_correct', models.PositiveIntegerField(default=0)),
                ('math_calc_correct', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='student_profile.sattest')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'test', '-started_at'], name='student_pro_student_704fc9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['course', 'cefr_level'], name='student_pro_course__be2216_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['word'], name='student_pro_word_e30982_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvocabularyprogress',
            index=models.Index(fields=['student', 'next_review_date'], name='student_pro_student_1cbb87_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvocabularyprogress',
            index=models.Index(fields=['student', 'mastery_level'], name='student_pro_student_65791d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentvocabularyprogress',
            unique_together={('student', 'word')},
        ),
    ]
