# Generated by Django 5.2.7 on 2025-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0014_enhance_event_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='student_pro_time_ac4899_idx',
            old_name='student_pr_start_t_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='student_pro_group_i_3e2a0e_idx',
            old_name='student_pr_group_i_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(db_column='time'),
        ),
    ]
