# Generated by Django 5.2.7 on 2025-11-23 12:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0015_rename_student_pr_start_t_idx_student_pro_time_ac4899_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20, unique=True, verbose_name='Section')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('coin_cost', models.PositiveIntegerField(default=50, help_text='Cost in coins to take this section')),
                ('coin_refund', models.PositiveIntegerField(default=10, help_text='Coins refunded if band score >= 5.0')),
                ('time_limit_minutes', models.PositiveIntegerField(help_text='Time limit for this section')),
                ('passing_band_score', models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='Minimum band score for coin refund', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))])),
                ('instructions', models.TextField(blank=True, help_text='Instructions shown before starting the exam')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IELTS Exam',
                'verbose_name_plural': 'IELTS Exams',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='IELTSAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('evaluating', 'AI Evaluating'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='payment_pending', max_length=20)),
                ('coins_paid', models.PositiveIntegerField(default=0)),
                ('coins_refunded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('raw_score', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Total points earned', max_digits=6)),
                ('band_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='IELTS band score (0.0 - 9.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('9.0'))])),
                ('ai_evaluation', models.JSONField(blank=True, default=dict, help_text='AI evaluation results and feedback')),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_payments', to='student_profile.studentcoins')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ielts_refunds', to='student_profile.studentcoins')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='student_profile.ieltsexam')),
            ],
            options={
                'verbose_name': 'IELTS Attempt',
                'verbose_name_plural': 'IELTS Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false_notgiven', 'True/False/Not Given'), ('matching_headings', 'Matching Headings'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('form_completion', 'Form Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flow_chart', 'Flow Chart Completion'), ('diagram_labeling', 'Diagram Labeling'), ('task1_academic', 'Task 1 (Academic)'), ('task1_general', 'Task 1 (General)'), ('task2_essay', 'Task 2 (Essay)'), ('introduction', 'Introduction & Interview'), ('long_turn', 'Long Turn (Cue Card)'), ('discussion', 'Two-way Discussion')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('passage_text', models.TextField(blank=True, help_text='Reading passage or listening script')),
                ('audio_file', models.FileField(blank=True, help_text='Audio for listening questions', null=True, upload_to='ielts/audio/%Y/%m/')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text='List of answer options for multiple choice questions')),
                ('correct_answer', models.JSONField(default=dict, help_text='Correct answer(s) - format varies by question type')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4)),
                ('speaking_prompts', models.JSONField(blank=True, default=list, help_text='Prompts for speaking questions')),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='Time limit for this question (0 = no limit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student_profile.ieltsexam')),
            ],
            options={
                'verbose_name': 'IELTS Question',
                'verbose_name_plural': 'IELTS Questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IELTSAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('selected_option', models.CharField(blank=True, max_length=255)),
                ('essay_content', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='ielts/speaking_responses/%Y/%m/')),
                ('transcription', models.TextField(blank=True, help_text='AI transcription of speaking response')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4)),
                ('ai_score', models.JSONField(blank=True, default=dict, help_text='Detailed AI scoring breakdown')),
                ('ai_feedback', models.TextField(blank=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student_profile.ieltsattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='student_profile.ieltsquestion')),
            ],
            options={
                'verbose_name': 'IELTS Answer',
                'verbose_name_plural': 'IELTS Answers',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='ieltsattempt',
            index=models.Index(fields=['student', 'status'], name='student_pro_student_488e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='ieltsattempt',
            index=models.Index(fields=['exam', 'status'], name='student_pro_exam_id_497d38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ieltsattempt',
            unique_together={('student', 'exam', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='ieltsanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
