# Generated by Django 5.2.7 on 2025-11-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0016_ieltsexam_ieltsattempt_ieltsquestion_ieltsanswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSExamDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('coin_cost', models.PositiveIntegerField(default=50)),
                ('coin_refund', models.PositiveIntegerField(default=10)),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('passing_band_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_reviewing', 'AI Reviewing'), ('ai_reviewed', 'AI Reviewed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('ai_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict, help_text='AI feedback and suggestions')),
                ('ai_quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI quality assessment (0-100)', max_digits=4, null=True)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Was this exam generated by AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exam_drafts', to=settings.AUTH_USER_MODEL)),
                ('published_exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_source', to='student_profile.ieltsexam')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IELTS Exam Draft',
                'verbose_name_plural': 'IELTS Exam Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExamGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('custom_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_exam_requests', to=settings.AUTH_USER_MODEL)),
                ('generated_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_request', to='student_profile.ieltsexamdraft')),
            ],
            options={
                'verbose_name': 'AI Exam Generation Request',
                'verbose_name_plural': 'AI Exam Generation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSQuestionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('passage_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ielts/drafts/audio/%Y/%m/')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(default=dict)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('speaking_prompts', models.JSONField(blank=True, default=list)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0)),
                ('ai_feedback', models.JSONField(blank=True, default=dict, help_text='AI suggestions for this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_questions', to='student_profile.ieltsexamdraft')),
            ],
            options={
                'verbose_name': 'IELTS Question Draft',
                'verbose_name_plural': 'IELTS Question Drafts',
                'ordering': ['exam_draft', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InboxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_approval_request', models.BooleanField(default=True)),
                ('email_on_exam_approved', models.BooleanField(default=True)),
                ('email_on_exam_rejected', models.BooleanField(default=True)),
                ('email_on_ai_review', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exam_submitted', 'Exam Submitted for Review'), ('ai_review_complete', 'AI Review Complete'), ('exam_approved', 'Exam Approved'), ('exam_rejected', 'Exam Rejected'), ('exam_published', 'Exam Published'), ('approval_request', 'Approval Request'), ('general', 'General Notification')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='student_profile.ieltsexamdraft')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ieltsexamdraft',
            index=models.Index(fields=['status', 'section'], name='student_pro_status_d4807c_idx'),
        ),
        migrations.AddIndex(
            model_name='ieltsexamdraft',
            index=models.Index(fields=['created_by', 'status'], name='student_pro_created_9ea41f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='student_pro_recipie_10f147_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='student_pro_created_2a965e_idx'),
        ),
    ]
