# Generated by Django 5.2.7 on 2025-11-24 08:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0018_remove_old_sat_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SATExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('coin_cost', models.PositiveIntegerField(default=50)),
                ('coin_refund', models.PositiveIntegerField(default=10)),
                ('passing_score', models.PositiveIntegerField(default=1000, help_text='Minimum score for refund (out of 1600)')),
                ('rw_total_questions', models.PositiveIntegerField(default=54)),
                ('rw_time_minutes', models.PositiveIntegerField(default=64)),
                ('math_total_questions', models.PositiveIntegerField(default=44)),
                ('math_time_minutes', models.PositiveIntegerField(default=70)),
                ('is_official', models.BooleanField(default=False, help_text='Official College Board practice test')),
                ('is_published', models.BooleanField(default=True)),
                ('test_number', models.PositiveIntegerField(blank=True, help_text='For official practice tests', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_profile_sat2025_exam',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='student_pro_is_publ_3c80fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SATAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='payment_pending', max_length=20)),
                ('coins_paid', models.PositiveIntegerField(default=0)),
                ('coins_refunded', models.PositiveIntegerField(default=0)),
                ('refund_eligible', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('reading_writing_score', models.PositiveIntegerField(blank=True, help_text='200-800', null=True)),
                ('math_score', models.PositiveIntegerField(blank=True, help_text='200-800', null=True)),
                ('total_score', models.PositiveIntegerField(blank=True, help_text='400-1600', null=True)),
                ('rw_correct', models.PositiveIntegerField(default=0, help_text='Out of 54')),
                ('math_correct', models.PositiveIntegerField(default=0, help_text='Out of 44')),
                ('rw_module1_correct', models.PositiveIntegerField(default=0)),
                ('rw_module2_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('math_module1_correct', models.PositiveIntegerField(default=0)),
                ('math_module2_difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict, help_text='AI analysis of performance by section and question type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sat_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='student_profile.satexam')),
            ],
            options={
                'db_table': 'student_profile_sat2025_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SATModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading_writing', 'Reading and Writing'), ('math', 'Math')], max_length=20)),
                ('module_number', models.PositiveIntegerField(help_text='1 or 2')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Module 1 is always medium. Module 2 adapts based on Module 1 performance', max_length=10)),
                ('time_minutes', models.PositiveIntegerField(help_text='32 min for RW modules, 35 min for Math modules')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='student_profile.satexam')),
            ],
            options={
                'db_table': 'student_profile_sat2025_module',
                'ordering': ['exam', 'section', 'module_number'],
            },
        ),
        migrations.CreateModel(
            name='SATQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('passage_text', models.TextField(blank=True, help_text='Reading passage or math problem context')),
                ('question_text', models.TextField()),
                ('rw_type', models.CharField(blank=True, choices=[('craft_structure', 'Craft and Structure'), ('information_ideas', 'Information and Ideas'), ('expression_ideas', 'Expression of Ideas'), ('standard_conventions', 'Standard English Conventions')], help_text='For Reading & Writing questions', max_length=30, null=True)),
                ('math_type', models.CharField(blank=True, choices=[('algebra', 'Algebra'), ('advanced_math', 'Advanced Math'), ('problem_solving', 'Problem-Solving & Data Analysis'), ('geometry', 'Geometry & Trigonometry')], help_text='For Math questions', max_length=30, null=True)),
                ('answer_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('spr', 'Student Produced Response (Grid-in)')], default='mcq', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text="List of answer choices for MCQ: ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.JSONField(help_text="For MCQ: {'answer': 'B'}. For SPR: {'answer': '42'}")),
                ('explanation', models.TextField(blank=True, help_text='Why the answer is correct')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('points', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student_profile.satmodule')),
            ],
            options={
                'db_table': 'student_profile_sat2025_question',
                'ordering': ['module', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='SATAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.JSONField(help_text="For MCQ: {'answer': 'B'}. For SPR: {'answer': '42'}")),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student_profile.satattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='student_profile.satquestion')),
            ],
            options={
                'db_table': 'student_profile_sat2025_answer',
                'ordering': ['attempt', 'question__question_number'],
            },
        ),
        migrations.AddIndex(
            model_name='satattempt',
            index=models.Index(fields=['student', '-created_at'], name='student_pro_student_067ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='satattempt',
            index=models.Index(fields=['student', 'status'], name='student_pro_student_8fec42_idx'),
        ),
        migrations.AddIndex(
            model_name='satmodule',
            index=models.Index(fields=['exam', 'section', 'module_number'], name='student_pro_exam_id_daece9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='satmodule',
            unique_together={('exam', 'section', 'module_number')},
        ),
        migrations.AddIndex(
            model_name='satquestion',
            index=models.Index(fields=['module', 'question_number'], name='student_pro_module__cc1d4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='satquestion',
            unique_together={('module', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='satanswer',
            index=models.Index(fields=['attempt', 'question'], name='student_pro_attempt_236b3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='satanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
