# Generated by Django 5.2.7 on 2025-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0019_satexam_satattempt_satmodule_satquestion_satanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Student Payment'), ('expense', 'Expense'), ('teacher_earning', 'Teacher Earning'), ('fine', 'Student Fine'), ('refund', 'Refund'), ('adjustment', 'Balance Adjustment'), ('monthly_fee', 'Monthly Fee')], db_index=True, help_text='Type of financial transaction', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('fees_applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Fee Log',
                'verbose_name_plural': 'Monthly Fee Logs',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
