# Generated by Codex on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def set_attendance_status_from_legacy_flag(apps, schema_editor):
    Attendance = apps.get_model('student_profile', 'Attendance')
    Attendance.objects.filter(is_present=True).update(attendance_status='present')
    Attendance.objects.filter(is_present=False).update(attendance_status='absent_unexcused')


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0021_studentbalance_balance_coins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(
                choices=[
                    ('present', 'Present'),
                    ('absent_unexcused', 'Absent (Unexcused)'),
                    ('absence_excused', 'Absence (Excused)'),
                ],
                default='present',
                help_text='Detailed attendance state used by automation.',
                max_length=20,
            ),
        ),
        migrations.RunPython(set_attendance_status_from_legacy_flag, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'group', '-date'], name='att_stu_grp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_status', '-date'], name='att_status_date_idx'),
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_tiyin', models.BigIntegerField(default=0, help_text='Current balance in tiyin. Negative means debt.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Account',
                'verbose_name_plural': 'Student Accounts',
                'ordering': ['student__username'],
            },
        ),
        migrations.CreateModel(
            name='AccountingActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_received', 'Payment received'), ('monthly_deduction', 'Monthly deduction'), ('debt_created', 'Debt created'), ('refund_issued', 'Refund issued'), ('attendance_marked', 'Attendance marked'), ('account_deactivated', 'Account deactivated'), ('account_frozen', 'Account frozen'), ('account_reactivated', 'Account reactivated'), ('system_action', 'System action')], db_index=True, max_length=40)),
                ('message', models.CharField(max_length=500)),
                ('amount_tiyin', models.BigIntegerField(blank=True, null=True)),
                ('balance_after_tiyin', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_activity_actor', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_logs', to='student_profile.attendance')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_activity_logs', to='student_profile.group')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_logs', to='student_profile.payment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_activity_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Activity Log',
                'verbose_name_plural': 'Accounting Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['-created_at', 'action_type'], name='acctlog_created_action_idx'),
                    models.Index(fields=['student', '-created_at'], name='acctlog_student_created_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='MonthlySubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('monthly_price_tiyin', models.BigIntegerField(help_text='Course monthly price in tiyin')),
                ('charged_tiyin', models.BigIntegerField(help_text='How much was deducted at month start')),
                ('refunded_tiyin', models.BigIntegerField(default=0, help_text='Refund returned to internal balance')),
                ('settlement_status', models.CharField(choices=[('none', 'No settlement'), ('deactivated', 'Deactivated after 3 unexcused absences'), ('frozen', 'Frozen after 3 excused absences')], default='none', max_length=20)),
                ('settlement_note', models.TextField(blank=True)),
                ('charged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_charges', to='student_profile.studentaccount')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_subscription_charges', to='student_profile.group')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_subscription_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Subscription Charge',
                'verbose_name_plural': 'Monthly Subscription Charges',
                'ordering': ['-year', '-month', '-charged_at'],
                'unique_together': {('student', 'group', 'year', 'month')},
            },
        ),
    ]
