# Generated by Django 5.2.9 on 2026-03-15 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0028_paymentauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('charge', 'Charge'), ('reversal', 'Reversal')], db_index=True, max_length=16)),
                ('is_active_charge', models.BooleanField(db_index=True, default=False, help_text='Only CHARGE entries can be active; set false once reversed.')),
                ('course_price_tiyin', models.BigIntegerField()),
                ('lesson_denominator', models.PositiveIntegerField(default=12)),
                ('per_lesson_fee_tiyin', models.BigIntegerField()),
                ('teacher_share_percent', models.PositiveIntegerField(default=40)),
                ('teacher_amount_tiyin', models.BigIntegerField()),
                ('company_amount_tiyin', models.BigIntegerField()),
                ('balance_before_tiyin', models.BigIntegerField()),
                ('balance_after_tiyin', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Attendance Charge',
                'verbose_name_plural': 'Attendance Charges',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyShareEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tiyin', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Company Share Entry',
                'verbose_name_plural': 'Company Share Entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='billing_mode',
            field=models.CharField(choices=[('fixed_planned', 'Fixed planned lesson count'), ('actual_monthly', 'Actual monthly calendar lesson count')], default='fixed_planned', help_text='How per-lesson fee denominator is resolved.', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='planned_monthly_lessons',
            field=models.PositiveIntegerField(default=12, help_text='Used when billing mode is fixed_planned.'),
        ),
        migrations.AddField(
            model_name='teacherearnings',
            name='entry_type',
            field=models.CharField(choices=[('accrual', 'Accrual'), ('reversal', 'Reversal')], db_index=True, default='accrual', max_length=16),
        ),
        migrations.AddField(
            model_name='teacherearnings',
            name='source_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('attendance', 'Attendance')], db_index=True, default='payment', max_length=16),
        ),
        migrations.AddField(
            model_name='teacherearnings',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student that generated this earning row.', limit_choices_to={'is_teacher': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_earning_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingactivitylog',
            name='action_type',
            field=models.CharField(choices=[('payment_received', 'Payment received'), ('monthly_deduction', 'Monthly deduction'), ('debt_created', 'Debt created'), ('refund_issued', 'Refund issued'), ('attendance_marked', 'Attendance marked'), ('account_deactivated', 'Account deactivated'), ('account_frozen', 'Account frozen'), ('account_reactivated', 'Account reactivated'), ('attendance_charged', 'Attendance charge posted'), ('attendance_reversed', 'Attendance charge reversed'), ('teacher_accrued', 'Teacher accrual posted'), ('company_share_recorded', 'Company share posted'), ('system_action', 'System action')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Student Payment'), ('expense', 'Expense'), ('teacher_earning', 'Teacher Earning'), ('attendance_charge', 'Attendance Charge'), ('attendance_charge_reversal', 'Attendance Charge Reversal'), ('company_share', 'Company Share Entry'), ('fine', 'Student Fine'), ('refund', 'Refund'), ('adjustment', 'Balance Adjustment'), ('monthly_fee', 'Monthly Fee')], db_index=True, help_text='Type of financial transaction', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacherearnings',
            name='payment',
            field=models.ForeignKey(blank=True, help_text="Source payment when source_type='payment'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_earnings', to='student_profile.payment'),
        ),
        migrations.AlterField(
            model_name='teacherearnings',
            name='payment_amount',
            field=models.BigIntegerField(help_text='Base amount in tiyin (payment amount or attendance lesson fee)'),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_charges', to='student_profile.studentaccount'),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_charges', to='student_profile.attendance'),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_charge_creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_charges', to='student_profile.group'),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='original_charge',
            field=models.ForeignKey(blank=True, help_text='Set for reversal rows to point to original charge row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='student_profile.attendancecharge'),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecharge',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_charge_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherearnings',
            name='attendance_charge',
            field=models.OneToOneField(blank=True, help_text="Source attendance charge when source_type='attendance'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_earning', to='student_profile.attendancecharge'),
        ),
        migrations.AddIndex(
            model_name='teacherearnings',
            index=models.Index(fields=['teacher', '-date'], name='teacher_earn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearnings',
            index=models.Index(fields=['source_type', 'entry_type'], name='teacher_earn_source_idx'),
        ),
        migrations.AddField(
            model_name='companyshareentry',
            name='charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_share_entry', to='student_profile.attendancecharge'),
        ),
        migrations.AddIndex(
            model_name='attendancecharge',
            index=models.Index(fields=['student', '-created_at'], name='att_charge_student_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecharge',
            index=models.Index(fields=['teacher', '-created_at'], name='att_charge_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecharge',
            index=models.Index(fields=['group', '-created_at'], name='att_charge_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'charge'), ('is_active_charge', True)), fields=('attendance',), name='uniq_active_charge_per_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendancecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'reversal')), fields=('original_charge',), name='uniq_reversal_per_charge'),
        ),
    ]
